version: 2
updates:
  - package-ecosystem: maven
    directory: /backend
    schedule:
      interval: weekly
    groups:
      maven-dependencies:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      npm-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

