spring:
  config:
    activate:
      on-profile: entra
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:https://login.microsoftonline.com/${ENTRA_TENANT_ID}/v2.0}
          audiences: ${OAUTH2_AUDIENCE:${ENTRA_API_CLIENT_ID}}
